name: Go Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clean Previous Build
      run: |
        go clean
        Remove-Item .\EDx52Display -Force -Recurse -ErrorAction SilentlyContinue
        Remove-Item .\Release.zip -ErrorAction SilentlyContinue

    - name: Build Project
      run: go build -o EDx52display.exe

    - name: Prepare Release Directory
      run: |
        mkdir EDx52Display
        Copy-Item -Path EDx52display.exe,conf.yaml,LICENSE,README.md,names,DepInclude -Destination .\EDx52Display -Recurse

    - name: Create Release Zip
      run: powershell Compress-Archive -Path .\EDx52Display\* -DestinationPath .\Release.zip

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: Release.zip
