name: Go Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., 0.1.2)"
        required: true
        default: "X.X.X"

jobs:
  build:
    runs-on: windows-latest
    outputs:
      sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Build Project
        run: go build -ldflags "-H=windowsgui -s -w" -v -o EDx52display-v${{ github.event.inputs.version }}.exe

      - name: Prepare Release Directory
        run: |
          mkdir EDx52Display-v${{ github.event.inputs.version }}
          Copy-Item -Path EDx52display-v${{ github.event.inputs.version }}.exe,conf.yaml,LICENSE,README.md,names,bin -Destination .\EDx52Display-v${{ github.event.inputs.version }} -Recurse

      - name: Create Release Zip
        run: powershell Compress-Archive -Path .\EDx52display-v${{ github.event.inputs.version }} -DestinationPath .\EDx52display-v${{ github.event.inputs.version }}-portable-amd64.zip

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: ./EDx52display-v${{ github.event.inputs.version }}-portable-amd64.zip

      - name: Get current commit SHA
        id: get_sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

  tag-and-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: release-zip

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ github.event.inputs.version }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: ./EDx52display-v${{ github.event.inputs.version }}-portable-amd64.zip