# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Clean Previous Build
      run: |
        rm -rf ./EDx52Display ./Release.zip || true

    - name: Build Project
      run: go build -o EDx52display.exe

    - name: Prepare Release Directory
      run: |
        mkdir EDx52Display
        cp EDx52display.exe conf.yaml LICENSE README.md names DepInclude ./EDx52Display

    - name: Create Release Zip
      run: zip -r Release.zip ./EDx52Display

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Release
        path: Release.zip
